### ISSUE TITLE
`gdformat` formats export hints with a space before the opening parenthesis

### ISSUE THREAD

**Issue by Calinou** [Scony/godot-gdscript-toolkit#100]
**gdformat version:** 3.2.7

Near the bottom of the [GDScript style guide](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html), you can see:

```gdscript
export(Jobs) var job = Jobs.KNIGHT
```

While it's not explicitly stated, it seems export hints should be written without a space before the opening parenthesis. However, `gdformat` will format it as such:

```gdscript
export (Jobs) var job = Jobs.KNIGHT
```

**Comment by Scony** [comment]
Well, since the GDScript guide is at its early stage I think we can alter it if necessary (thus we can discuss a little bit). I'm open to both styles. I've picked the version w/o space by default since it was more clear to me and it was also slightly distinguishable from functions. On the other hand `export(Jobs)` is more in line with functions and it looks less like a standalone expression. Which option do you prefer @Calinou and maybe @NathanLovato ?

**Comment by Calinou** [comment]
I prefer `export(Jobs)` myself (without a space).

**Comment by NathanLovato** [comment]
I don't have an opinion on that. export(hint) is fine by me. Thanks!
