### ISSUE TITLE
Show line numbers when using `gdformat -c` (with `--verbose`)

### ISSUE THREAD

**Issue by Speedphoenix** [Scony/godot-gdscript-toolkit#109]
# The current problem

I currently cannot use an external program for formatting like `gdformat` without the `-c` option, but I can use a linter that does not modify the files like `gdlint`.

Problem is, `gdlint` does not warn about formatting errors, and `gdformat -c` only shows which files would be modified, not where inside the files.

# Proposed solution

Add an option to `gdlint` to print the line numbers, and possibly the issues found.  

I suggest using `--verbose`, which would work for both with and without the `-c` option

For example with this file:

```gdscript
# test.gd
extends TextureRect

var test= 1


func _ready():
	pass
```

Example outputs of `gdformat -c --verbose test.gd`:
```
would reformat test.gd
Line 4 would be reformatted
# or
test.gd:4: Would be reformatted
# or
test.gd:4: Error: missing whitespace before '='
```

And without `-c`, but with the `--verbose` option the output could look like `Line 4: Reformatted`

Admittedly you wouldn't use `--verbose` without `-c` much, but it might be useful when looking to improve oneself

**Comment by Aareon** [comment]
Might I propose `--diff` as an alternative? IMO this would make more sense for this purpose. With this flag, the formatter would generate and output a diff of changes instead of modifying the file. I feel like this would be clearer as to what it should do than `--verbose`.

This behavior is also implemented in [black](https://github.com/psf/black) using the `--diff` argument. Whereas `--verbose` in black only outputs to stderr about files not changed/ignored.

**Comment by Scony** [comment]
Well, `--diff` may be a good idea. I'll try to implement it in the next release (ca. 1 month)
