### ISSUE TITLE
spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by DPMakerQB** [Scony/godot-gdscript-toolkit#170]
Hi! I'm getting the error `spawn ENAMETOOLONG` when using gdformat.

Perhaps it's because there's too many characters in my script?

Lines: 559
Characters: 32,296

**Comment by Scony** [comment]
hi, I cannot reproduce using a file of similar size. Could you please attach full stacktrace? Or (if possible) the file which is causing the problem.

**Comment by HolonProduction** [comment]
`spawn ENAMETOOLONG` seems to indicate, that the length of parameters passed to the commandline exceeds the max char amount. Since the gdformat command recieves the file name as input this maximum will propably not be reached when using the cli. But in the vscode plugin the code is passed as arg and not the file name. So this is propably only reproducable with vscode (have not looked into emacs).

https://stackoverflow.com/questions/66092260/error-spawn-enametoolong-when-trying-to-send-a-long-string-from-nodejs-to-pytho

**Comment by Scony** [comment]
VSCode extension is no longer part of this repo.
