### ISSUE TITLE
Tabs shouldn't be removed on empty lines that are still within function scope

### ISSUE THREAD

**Issue by robbertzzz** [Scony/godot-gdscript-toolkit#186]
Wrong:
![image](https://user-images.githubusercontent.com/7684647/207084133-3cde2f04-5188-473d-8562-58dea33b9696.png)

Correct:
![image](https://user-images.githubusercontent.com/7684647/207084186-074fb98b-1c62-40aa-bc9e-a39a97b61164.png)

Tabs are rendered in Godot, which helps visualise scope. If an empty line is both preceded and followed by lines within the same scope, it should keep the same indentation level.

**Comment by Scony** [comment]
@mattkanwisher @robbertzzz is it in 3.x or `master`?

**Comment by robbertzzz** [comment]
@Scony we're using the latest Godot 4.0 beta, so I assume @mattkanwisher pulled the latest version here. I'll let him confirm that.

**Comment by Scony** [comment]
nvm. I've checked and this is actually expected behavior. Trailing whitespaces are not welcome.

**Comment by robbertzzz** [comment]
> nvm. I've checked and this is actually expected behavior. Trailing whitespaces are not welcome.

That's not what this issue is about, this is about indentation.

**Comment by Scony** [comment]
@robbertzzz the indentation doesn't have to be continuous (i.e. having blank lines with trailing whitespace)

**Comment by robbertzzz** [comment]
The indentation is continuous by default in the script editor. Indentation also improves usability because Godot's script editor renders the tabs; it shows you you're still in the same scope.

There's nothing that points to whether or not indentation should be continuous in the style guide, but since keeping indentation is the default in the editor it should be the default in this tool too.

**Comment by Scony** [comment]
@robbertzzz tabs being rendered in the editor is just a side effect - not an intended behavior. This is not true that Godot editor keeps such tabs on purpose. Whenever you press `ENTER` in the editor, you will land in the new line with the extra tabs added. I think the tabs are there only for you to continue typing. The problem is - whenever you hit `ENTER` again, the tabs of the blank lines are not removed (modern IDEs remove such trailing whitespaces). I think it's rather a bug in the editor. Please note that such behavior is being marked as wrong by e.g. git vcs. Not to mention black formatter for python which is a role model for gdtoolkit.

**Comment by marcospb19** [comment]
This is a bit annoying. Given this code:

```gdscript
				raycast.target_position.y = randf_range(-weapon.spread, weapon.spread)

				raycast.force_raycast_update()
```

If I want to add a line in-between the two, I need to press TAB till it's indented at the same level.

Or, use my mouse to click at the end of the first line, then press ENTER, but it's annoying to use the mouse every time, I just want to add a new line, this is very common when editing a file.

How do y'all do it? I'd appreciate tips or shortcuts that could help.

---

I kinda agree with OP here, it makes sense to have trailing whitespace in Godot because external editor support is bad and we're limited to what the Godot editor can do.

When using Black with Python it doesn't matter because you have good IDEs to handle indentation smartly, however, this isn't the case for Godot.

**Comment by marcospb19** [comment]
FWIW, here is the patch I applied locally to have this working for me locally:

```diff
diff --git a/gdtoolkit/formatter/block.py b/gdtoolkit/formatter/block.py
@@ -77,15 +77,16 @@ def reconstruct_blank_lines_in_range(
     comments_in_range = context.standalone_comments[begin + 1 : end]
     reconstructed_lines = []
     for line_no, comment in zip(range(begin + 1, end), comments_in_range):
+        line = context.gdscript_code_lines[line_no]
         if comment is not None:
             prefix = (
                 context.indent_string
-                if not context.gdscript_code_lines[line_no].startswith("#")
+                if not line.startswith("#")
                 else ""
             )
             reconstructed_lines.append(prefix + comment)
         else:
-            reconstructed_lines.append("")
+            reconstructed_lines.append(line)
     reconstructed_lines = _squeeze_lines(reconstructed_lines)
     return list(zip([None for _ in range(begin + 1, end)], reconstructed_lines))
```
