### ISSUE TITLE
Stopping two new lines after function call

### ISSUE THREAD

**Issue by fire** [Scony/godot-gdscript-toolkit#57]
How do you stop this linter from making two new lines after the function call def?

**Comment by Scony** [comment]
You mean formatter putting 2 newlines after function definition?
```
func foo():
    pass


func bar():
    pass
```

**Comment by fire** [comment]
Yes, I only want one.

**Comment by Scony** [comment]
Well, it's in par with GDScript style guideline (https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_styleguide.html#blank-lines) and hence 2 lines are enforced. The only situation where 1 line is set is when functions are enclosed in block like;
```
class X:
    func foo():
        pass

    func bar():
        pass
```

And since only one (official) guideline is supported, it's not possible to configure it, sorry.
